# Generated by Django 6.0.2 on 2026-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/Product/')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
