# Generated by Django 6.0.2 on 2026-02-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_adress',
            new_name='delivery_address',
        ),
    ]
